/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import BD.RegisterPetFunctions;
import BD.UpdatePetFunctions;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marie
 */
public class UpdatePet extends javax.swing.JFrame {
    ButtonGroup buttonGroup = new ButtonGroup();
    private RegisterPetFunctions registerPetFunctions;
    private UpdatePetFunctions updatePetFunctions;
    /**
     * Creates new form UpdatePet
     */
    public UpdatePet() {
        initComponents();
        registerPetFunctions = new RegisterPetFunctions();
        updatePetFunctions = new UpdatePetFunctions();
        DefaultTableModel model = updatePetFunctions.executePetQuery("7");
        PetsjTable.setModel(model);
        buttonGroup.add(petNamejRadioButton);
        buttonGroup.add(petStatusjRadioButton);
        buttonGroup.add(petTypejRadioButton);
        buttonGroup.add(petColorjRadioButton);
        buttonGroup.add(petBreedjRadioButton);
        buttonGroup.add(petChipjRadioButton);
        buttonGroup.add(petDateInjRadioButton);
        buttonGroup.add(petAmountSpentjRadioButton);
        changeAmountSpentjPanel.setVisible(false);
        changePetBreedjPanel.setVisible(false);
        changePetChipjPanel.setVisible(false);
        changeDateInjPanel.setVisible(false);
        changePetColor.setVisible(false);
        changePetNamejPanel.setVisible(false);
        changePetStatusjPanel.setVisible(false);
        changePetTypejPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TitleLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetsjTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        petNamejRadioButton = new javax.swing.JRadioButton();
        petStatusjRadioButton = new javax.swing.JRadioButton();
        petTypejRadioButton = new javax.swing.JRadioButton();
        petColorjRadioButton = new javax.swing.JRadioButton();
        petChipjRadioButton = new javax.swing.JRadioButton();
        petBreedjRadioButton = new javax.swing.JRadioButton();
        petDateInjRadioButton = new javax.swing.JRadioButton();
        petAmountSpentjRadioButton = new javax.swing.JRadioButton();
        changePetNamejPanel = new javax.swing.JPanel();
        newNamejLabel = new javax.swing.JLabel();
        newNamejTextField = new javax.swing.JTextField();
        changeDateInjPanel = new javax.swing.JPanel();
        currentDatejLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        changePetTypejPanel = new javax.swing.JPanel();
        neTypejLabel = new javax.swing.JLabel();
        petTypesjComboBox = new javax.swing.JComboBox<>();
        changePetStatusjPanel = new javax.swing.JPanel();
        newStatusjLabel = new javax.swing.JLabel();
        statusjComboBox = new javax.swing.JComboBox<>();
        changePetColor = new javax.swing.JPanel();
        newColorjLabel = new javax.swing.JLabel();
        colorjComboBox = new javax.swing.JComboBox<>();
        changeAmountSpentjPanel = new javax.swing.JPanel();
        newAmountjLabel = new javax.swing.JLabel();
        newAmountjTextField = new javax.swing.JTextField();
        changePetBreedjPanel = new javax.swing.JPanel();
        newBreedjLabel = new javax.swing.JLabel();
        breedjComboBox = new javax.swing.JComboBox<>();
        changePetChipjPanel = new javax.swing.JPanel();
        newChipjLabel = new javax.swing.JLabel();
        newChipjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(840, 635));
        setMinimumSize(new java.awt.Dimension(840, 635));

        jPanel1.setBackground(new java.awt.Color(207, 232, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setForeground(new java.awt.Color(0, 102, 153));

        TitleLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        TitleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel1.setText("Update");
        TitleLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(TitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TitleLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Click on the pet you want to update");

        PetsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(PetsjTable);

        nextButton.setBackground(new java.awt.Color(0, 102, 153));
        nextButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("UPDATE");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Choose what you want to update");

        petNamejRadioButton.setText("Pet Name");
        petNamejRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petNamejRadioButtonItemStateChanged(evt);
            }
        });
        petNamejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNamejRadioButtonActionPerformed(evt);
            }
        });

        petStatusjRadioButton.setText("Pet Status");
        petStatusjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petStatusjRadioButtonItemStateChanged(evt);
            }
        });
        petStatusjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petStatusjRadioButtonActionPerformed(evt);
            }
        });

        petTypejRadioButton.setText("Pet Type");
        petTypejRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petTypejRadioButtonItemStateChanged(evt);
            }
        });
        petTypejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petTypejRadioButtonActionPerformed(evt);
            }
        });

        petColorjRadioButton.setText("Pet Color");
        petColorjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petColorjRadioButtonItemStateChanged(evt);
            }
        });
        petColorjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petColorjRadioButtonActionPerformed(evt);
            }
        });

        petChipjRadioButton.setText("Pet Chip");
        petChipjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petChipjRadioButtonItemStateChanged(evt);
            }
        });
        petChipjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petChipjRadioButtonActionPerformed(evt);
            }
        });

        petBreedjRadioButton.setText("Pet Breed");
        petBreedjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petBreedjRadioButtonItemStateChanged(evt);
            }
        });
        petBreedjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petBreedjRadioButtonActionPerformed(evt);
            }
        });

        petDateInjRadioButton.setText("Date In");
        petDateInjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petDateInjRadioButtonItemStateChanged(evt);
            }
        });
        petDateInjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petDateInjRadioButtonActionPerformed(evt);
            }
        });

        petAmountSpentjRadioButton.setText("Amount Spent");
        petAmountSpentjRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                petAmountSpentjRadioButtonItemStateChanged(evt);
            }
        });
        petAmountSpentjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petAmountSpentjRadioButtonActionPerformed(evt);
            }
        });

        changePetNamejPanel.setBackground(new java.awt.Color(207, 232, 255));

        newNamejLabel.setBackground(new java.awt.Color(0, 51, 102));
        newNamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newNamejLabel.setForeground(new java.awt.Color(0, 51, 102));
        newNamejLabel.setText("New Name:");

        javax.swing.GroupLayout changePetNamejPanelLayout = new javax.swing.GroupLayout(changePetNamejPanel);
        changePetNamejPanel.setLayout(changePetNamejPanelLayout);
        changePetNamejPanelLayout.setHorizontalGroup(
            changePetNamejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetNamejPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        changePetNamejPanelLayout.setVerticalGroup(
            changePetNamejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetNamejPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetNamejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newNamejLabel))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        changeDateInjPanel.setBackground(new java.awt.Color(207, 232, 255));

        currentDatejLabel.setBackground(new java.awt.Color(0, 51, 102));
        currentDatejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentDatejLabel.setForeground(new java.awt.Color(0, 51, 102));
        currentDatejLabel.setText("New Date:");

        javax.swing.GroupLayout changeDateInjPanelLayout = new javax.swing.GroupLayout(changeDateInjPanel);
        changeDateInjPanel.setLayout(changeDateInjPanelLayout);
        changeDateInjPanelLayout.setHorizontalGroup(
            changeDateInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeDateInjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(currentDatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        changeDateInjPanelLayout.setVerticalGroup(
            changeDateInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeDateInjPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(changeDateInjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentDatejLabel)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        changePetTypejPanel.setBackground(new java.awt.Color(207, 232, 255));

        neTypejLabel.setBackground(new java.awt.Color(0, 51, 102));
        neTypejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        neTypejLabel.setForeground(new java.awt.Color(0, 51, 102));
        neTypejLabel.setText("New Type:");

        petTypesjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                petTypesjComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout changePetTypejPanelLayout = new javax.swing.GroupLayout(changePetTypejPanel);
        changePetTypejPanel.setLayout(changePetTypejPanelLayout);
        changePetTypejPanelLayout.setHorizontalGroup(
            changePetTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetTypejPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(neTypejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petTypesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        changePetTypejPanelLayout.setVerticalGroup(
            changePetTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetTypejPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neTypejLabel)
                    .addComponent(petTypesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        changePetStatusjPanel.setBackground(new java.awt.Color(207, 232, 255));

        newStatusjLabel.setBackground(new java.awt.Color(0, 51, 102));
        newStatusjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newStatusjLabel.setForeground(new java.awt.Color(0, 51, 102));
        newStatusjLabel.setText("New Status:");

        statusjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                statusjComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        statusjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusjComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePetStatusjPanelLayout = new javax.swing.GroupLayout(changePetStatusjPanel);
        changePetStatusjPanel.setLayout(changePetStatusjPanelLayout);
        changePetStatusjPanelLayout.setHorizontalGroup(
            changePetStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetStatusjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newStatusjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        changePetStatusjPanelLayout.setVerticalGroup(
            changePetStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetStatusjPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStatusjLabel)
                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        changePetColor.setBackground(new java.awt.Color(207, 232, 255));

        newColorjLabel.setBackground(new java.awt.Color(0, 51, 102));
        newColorjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newColorjLabel.setForeground(new java.awt.Color(0, 51, 102));
        newColorjLabel.setText("New Color:");

        colorjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                colorjComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout changePetColorLayout = new javax.swing.GroupLayout(changePetColor);
        changePetColor.setLayout(changePetColorLayout);
        changePetColorLayout.setHorizontalGroup(
            changePetColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetColorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newColorjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        changePetColorLayout.setVerticalGroup(
            changePetColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetColorLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newColorjLabel)
                    .addComponent(colorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        changeAmountSpentjPanel.setBackground(new java.awt.Color(207, 232, 255));

        newAmountjLabel.setBackground(new java.awt.Color(0, 51, 102));
        newAmountjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newAmountjLabel.setForeground(new java.awt.Color(0, 51, 102));
        newAmountjLabel.setText("New Amount:");

        javax.swing.GroupLayout changeAmountSpentjPanelLayout = new javax.swing.GroupLayout(changeAmountSpentjPanel);
        changeAmountSpentjPanel.setLayout(changeAmountSpentjPanelLayout);
        changeAmountSpentjPanelLayout.setHorizontalGroup(
            changeAmountSpentjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeAmountSpentjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newAmountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        changeAmountSpentjPanelLayout.setVerticalGroup(
            changeAmountSpentjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeAmountSpentjPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changeAmountSpentjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAmountjLabel))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        changePetBreedjPanel.setBackground(new java.awt.Color(207, 232, 255));

        newBreedjLabel.setBackground(new java.awt.Color(0, 51, 102));
        newBreedjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newBreedjLabel.setForeground(new java.awt.Color(0, 51, 102));
        newBreedjLabel.setText("New Breed:");

        breedjComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                breedjComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout changePetBreedjPanelLayout = new javax.swing.GroupLayout(changePetBreedjPanel);
        changePetBreedjPanel.setLayout(changePetBreedjPanelLayout);
        changePetBreedjPanelLayout.setHorizontalGroup(
            changePetBreedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetBreedjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newBreedjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breedjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        changePetBreedjPanelLayout.setVerticalGroup(
            changePetBreedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetBreedjPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetBreedjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBreedjLabel)
                    .addComponent(breedjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        changePetChipjPanel.setBackground(new java.awt.Color(207, 232, 255));

        newChipjLabel.setBackground(new java.awt.Color(0, 51, 102));
        newChipjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newChipjLabel.setForeground(new java.awt.Color(0, 51, 102));
        newChipjLabel.setText("New Chip:");

        javax.swing.GroupLayout changePetChipjPanelLayout = new javax.swing.GroupLayout(changePetChipjPanel);
        changePetChipjPanel.setLayout(changePetChipjPanelLayout);
        changePetChipjPanelLayout.setHorizontalGroup(
            changePetChipjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetChipjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newChipjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newChipjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        changePetChipjPanelLayout.setVerticalGroup(
            changePetChipjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePetChipjPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(changePetChipjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newChipjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newChipjLabel))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changePetNamejPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(petNamejRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(petStatusjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(petTypejRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(petColorjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(petChipjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(petBreedjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(petDateInjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(petAmountSpentjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(534, Short.MAX_VALUE)
                    .addComponent(changePetStatusjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(544, Short.MAX_VALUE)
                    .addComponent(changePetTypejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(544, Short.MAX_VALUE)
                    .addComponent(changePetColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(538, Short.MAX_VALUE)
                    .addComponent(changeAmountSpentjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(544, Short.MAX_VALUE)
                    .addComponent(changePetBreedjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(538, Short.MAX_VALUE)
                    .addComponent(changePetChipjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(525, Short.MAX_VALUE)
                    .addComponent(changeDateInjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petNamejRadioButton)
                            .addComponent(petStatusjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petTypejRadioButton)
                            .addComponent(petColorjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petChipjRadioButton)
                            .addComponent(petBreedjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petDateInjRadioButton)
                            .addComponent(petAmountSpentjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePetNamejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(296, Short.MAX_VALUE)
                    .addComponent(changePetStatusjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(changePetTypejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(159, 159, 159)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(changePetColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(159, 159, 159)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(296, Short.MAX_VALUE)
                    .addComponent(changeAmountSpentjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(168, 168, 168)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(changePetBreedjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(159, 159, 159)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(297, Short.MAX_VALUE)
                    .addComponent(changePetChipjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addComponent(changeDateInjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(147, 147, 147)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void petNamejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNamejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petNamejRadioButtonActionPerformed

    private void petStatusjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petStatusjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petStatusjRadioButtonActionPerformed

    private void petTypejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petTypejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petTypejRadioButtonActionPerformed

    private void petColorjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petColorjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petColorjRadioButtonActionPerformed

    private void petChipjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petChipjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petChipjRadioButtonActionPerformed

    private void petBreedjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petBreedjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petBreedjRadioButtonActionPerformed

    private void petDateInjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petDateInjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petDateInjRadioButtonActionPerformed

    private void petAmountSpentjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petAmountSpentjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petAmountSpentjRadioButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       int filaSeleccionada = PetsjTable.getSelectedRow();

        if (filaSeleccionada != -1) { // Asegurarse de que haya una fila seleccionada
            // Obtener el valor de la primera columna (columna 0) de la fila seleccionada
            Object valorCelda = PetsjTable.getValueAt(filaSeleccionada, 0);
            if (valorCelda != null) {
                String valorComoString = valorCelda.toString();
                int idPet = Integer.parseInt(valorComoString);
                System.out.println(idPet);
                if (petNamejRadioButton.isSelected()) {
                    String newName = newNamejTextField.getText();
                    String result = updatePetFunctions.updatePetName(idPet, newName);
                }else if (petChipjRadioButton.isSelected()) {
                    int newChip = Integer.valueOf(newChipjTextField.getText());
                    String result = updatePetFunctions.updatePetChip(idPet, newChip);
                }else if (petAmountSpentjRadioButton.isSelected()) {
                    int newAmount = Integer.valueOf(newAmountjTextField.getText());
                    String result = updatePetFunctions.updatePetAmountSpent(7, idPet, newAmount);
                }else if (petDateInjRadioButton.isSelected()) {
                    int newAmount = Integer.valueOf(newAmountjTextField.getText());
                    String result = updatePetFunctions.updatePetAmountSpent(7, idPet, newAmount);
                }
            }
            if (petNamejRadioButton.isSelected()) {
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
        }
        DefaultTableModel model = updatePetFunctions.executePetQuery("7");
        PetsjTable.setModel(model);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void petNamejRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petNamejRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetNamejPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetNamejPanel.setVisible(false);
    }//GEN-LAST:event_petNamejRadioButtonItemStateChanged

    private void petStatusjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petStatusjRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetStatusjPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetStatusjPanel.setVisible(false);
    }//GEN-LAST:event_petStatusjRadioButtonItemStateChanged

    private void petTypejRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petTypejRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetTypejPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetTypejPanel.setVisible(false);
    }//GEN-LAST:event_petTypejRadioButtonItemStateChanged

    private void petColorjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petColorjRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetColor.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetColor.setVisible(false);
    }//GEN-LAST:event_petColorjRadioButtonItemStateChanged

    private void petChipjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petChipjRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetChipjPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetChipjPanel.setVisible(false);
    }//GEN-LAST:event_petChipjRadioButtonItemStateChanged

    private void petBreedjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petBreedjRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changePetBreedjPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changePetBreedjPanel.setVisible(false);
    }//GEN-LAST:event_petBreedjRadioButtonItemStateChanged

    private void petAmountSpentjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petAmountSpentjRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changeAmountSpentjPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changeAmountSpentjPanel.setVisible(false);
    }//GEN-LAST:event_petAmountSpentjRadioButtonItemStateChanged

    private void petDateInjRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_petDateInjRadioButtonItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            changeDateInjPanel.setVisible(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) 
           changeDateInjPanel.setVisible(false);
    }//GEN-LAST:event_petDateInjRadioButtonItemStateChanged

    private void petTypesjComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_petTypesjComboBoxPopupMenuWillBecomeVisible
        petTypesjComboBox.removeAllItems();
        // Llama a la función para obtener la lista de tipos de mascotas
        List<String> petTypes = registerPetFunctions.getAllPetTypes();
        // Agrega los valores al ComboBox
        for (String petType : petTypes) {
            petTypesjComboBox.addItem(petType);
        }
    }//GEN-LAST:event_petTypesjComboBoxPopupMenuWillBecomeVisible

    private void statusjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusjComboBoxActionPerformed
      
    }//GEN-LAST:event_statusjComboBoxActionPerformed

    private void colorjComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_colorjComboBoxPopupMenuWillBecomeInvisible
        colorjComboBox.removeAllItems();
        // Llama a la función para obtener la lista de tipos de mascotas
        List<String> petColors = registerPetFunctions.getAllPetColors();
        // Agrega los valores al ComboBox
        for (String petColor : petColors) {
            colorjComboBox.addItem(petColor);
        }
    }//GEN-LAST:event_colorjComboBoxPopupMenuWillBecomeInvisible

    private void breedjComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_breedjComboBoxPopupMenuWillBecomeVisible
        // Verifica si hay una fila seleccionada
        int selectedRow = PetsjTable.getSelectedRow();
        if (selectedRow != -1) {
            // Obtiene el valor de la primera columna de la fila seleccionada
            Object selectedValue = PetsjTable.getValueAt(selectedRow, 4);
            if (selectedValue != null) {
                String selectedValueStr = selectedValue.toString(); // Convierte a String si es necesario
                System.out.println(selectedValueStr);
                breedjComboBox.removeAllItems();
                // Llama a la función para obtener la lista de tipos de mascotas
                List<String> petBreeds = registerPetFunctions.getBreedsByPetType(selectedValueStr);
                for (String petBreed : petBreeds) {
                    breedjComboBox.addItem(petBreed);
                }
            } else {
                // Muestra un JOptionPane en caso de valor nulo
                JOptionPane.showMessageDialog(null, "The selected value is null", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Muestra un JOptionPane en caso de que no haya fila seleccionada
            JOptionPane.showMessageDialog(null, "No Row Selected", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_breedjComboBoxPopupMenuWillBecomeVisible

    private void statusjComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_statusjComboBoxPopupMenuWillBecomeVisible
        // Llama a la función getAllPetStatus para obtener la lista de estados de mascotas
        List<String> petStatusList = registerPetFunctions.getAllPetStatus();
        // Limpia el JComboBox para eliminar elementos previos si es necesario
        statusjComboBox.removeAllItems();
        // Agrega los estados de mascotas a JComboBox
        for (String status : petStatusList) {
            statusjComboBox.addItem(status);
        
        }
    }//GEN-LAST:event_statusjComboBoxPopupMenuWillBecomeVisible
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePet().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PetsjTable;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JComboBox<String> breedjComboBox;
    private javax.swing.JPanel changeAmountSpentjPanel;
    private javax.swing.JPanel changeDateInjPanel;
    private javax.swing.JPanel changePetBreedjPanel;
    private javax.swing.JPanel changePetChipjPanel;
    private javax.swing.JPanel changePetColor;
    private javax.swing.JPanel changePetNamejPanel;
    private javax.swing.JPanel changePetStatusjPanel;
    private javax.swing.JPanel changePetTypejPanel;
    private javax.swing.JComboBox<String> colorjComboBox;
    private javax.swing.JLabel currentDatejLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel neTypejLabel;
    private javax.swing.JLabel newAmountjLabel;
    private javax.swing.JTextField newAmountjTextField;
    private javax.swing.JLabel newBreedjLabel;
    private javax.swing.JLabel newChipjLabel;
    private javax.swing.JTextField newChipjTextField;
    private javax.swing.JLabel newColorjLabel;
    private javax.swing.JLabel newNamejLabel;
    private javax.swing.JTextField newNamejTextField;
    private javax.swing.JLabel newStatusjLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton petAmountSpentjRadioButton;
    private javax.swing.JRadioButton petBreedjRadioButton;
    private javax.swing.JRadioButton petChipjRadioButton;
    private javax.swing.JRadioButton petColorjRadioButton;
    private javax.swing.JRadioButton petDateInjRadioButton;
    private javax.swing.JRadioButton petNamejRadioButton;
    private javax.swing.JRadioButton petStatusjRadioButton;
    private javax.swing.JRadioButton petTypejRadioButton;
    private javax.swing.JComboBox<String> petTypesjComboBox;
    private javax.swing.JComboBox<String> statusjComboBox;
    // End of variables declaration//GEN-END:variables

    private int IntegerValueOf(String valorComoString) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
